import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "brutal-bg": "#4a0404",
        "brutal-text": "#fff5e6",
        "brutal-accent": "#1a0101",
        "primary": "#fff5e6",
        "on-error": "#690005",
        "surface-container-highest": "#39342f",
        "primary-fixed": "#ede1c8",
        "on-tertiary-container": "#5c5445",
        "surface-container-high": "#1a0101",
        "outline": "#ff9e96",
        "on-primary-container": "#fff5e6",
        "on-secondary-fixed-variant": "#8a1a1a",
        "tertiary-container": "#d4c9b5",
        "on-background": "#fff5e6",
        "tertiary": "#f1e5d1",
        "inverse-primary": "#665e49",
        "on-tertiary-fixed": "#201b0f",
        "tertiary-fixed": "#ede1cd",
        "surface-container-low": "#2a0202",
        "primary-fixed-dim": "#d0c6ad",
        "secondary": "#ffb3ac",
        "secondary-container": "#8e1c1c",
        "on-primary": "#4a0404",
        "on-tertiary-fixed-variant": "#4d4637",
        "tertiary-fixed-dim": "#d1c5b2",
        "surface-variant": "#2a0202",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "secondary-fixed": "#ffdad6",
        "on-primary-fixed": "#201b0b",
        "outline-variant": "#8e1c1c",
        "primary-container": "#1a0101",
        "surface-tint": "#fff5e6",
        "on-tertiary": "#363022",
        "surface": "#4a0404",
        "on-surface": "#fff5e6",
        "inverse-on-surface": "#4a0404",
        "surface-container-lowest": "#1a0101",
        "on-surface-variant": "#fff5e6",
        "secondary-fixed-dim": "#ffb3ac",
        "inverse-surface": "#fff5e6",
        "on-secondary-fixed": "#410003",
        "on-secondary": "#680007",
        "on-primary-fixed-variant": "#4d4633",
        "on-secondary-container": "#ff9e96",
        "surface-dim": "#4a0404",
        "error": "#ffb4ab",
        "background": "#4a0404",
        "surface-container": "#2a0202",
        "surface-bright": "#6a0505"
      },
      fontFamily: {
        "headline-md": ["var(--font-playfair)", "serif"],
        "body-md": ["var(--font-playfair)", "serif"],
        "body-lg": ["var(--font-playfair)", "serif"],
        "label-sm": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
        "headline-lg": ["var(--font-playfair)", "serif"],
        "mono": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
export default config;
